# ------------------------------------------------------------------------------
#
# Creates a Docker workflow in order to have Zookeeper, Kafka and
# Kafka Manager running for development.
#
# @author diogo.munaro
#
# @version 1.00.00 - diogo.munaro - 2016/11/18 - Initial version.
#
# ------------------------------------------------------------------------------

version: '2'
services:
  zookeeper-server:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka-server:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-server:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
